const Application_Constant = {
    skipText:'Sauter',
    Reparer_devient_facile_Text:'Réparer devient facile',
    Lorem_Ipsum_text:'Lorem Ipsum, giving information on its origins, as well as a random Lipsum generator.',
    now_save_text:'Maintenant, économisez votre temps',
    mobile_login_text:'Se connecter avec un téléphone portable',
    email_login_text:'Se connecter avec une adresse mail',
    register_free_text:'Inscrivez-vous gratuitement maintenant!',
    register_text:'S\'inscrire',
    password_text:'Mot de passe',
    email_address_text:'Adresse mail',
    forgotpassword_text:"Mot de passe oublié ?",
    new_coplete_text:'Nouveau complete',
    telephone_text:'Telephone',
    Nom_de_familee:'Nom de familee',
    Addresse_text:   "Addresse",
    Anniversarie_text:  ' Anniversarie',
    Homme_text:'Homme',
    Moyen_text: 'Moyen de paiement',
    Type_de_client_text:'Type de client',
    Particulier_text:    'Particulier',
    Entreprise_text:     'Entreprise',
    Clienten_compte_text:   'Client en compte',
    Sélectionnezun_avatar_text:   ' Sélectionnez un avatar',
    Ajouter_une_photo_text: 'Ajouter une photo',
    Prendre_votre_photo_text: 'Prendre votre photo',
    J_accepte_les_text: 'J accepte les',
    term_cinditions: ' termes et conditions',
    hop_assist:' d Hop assist',
    Inscrire_Maintenant_text:' Inscrire Maintenant',
    Veuillez_remplir_text: 'Veuillez remplir les champs obligatoires pour continuer',
    Adresse_de_dépannage_text:'Adresse de dépannage',
    Complement_De_Adresse_text:'Complement De Adresse',
    Quelle_text:'Quelle Est La Panne',  
}

export default Application_Constant;