const Application_Constant = {
    color_green_code:'#01A2C4',
    light_color:'#CAD0D6',
    skipText:'Sauter',
    Reparer_devient_facile_Text:'Réparer devient facile',
    Lorem_Ipsum_text:'Lorem Ipsum, giving information on its origins, as well as a random Lipsum generator.',
    now_save_text:'Maintenant, économisez votre temps',
    mobile_login_text:'Se connecter avec un téléphone portable',
    email_login_text:'Se connecter avec une adresse mail',
    register_free_text:'Inscrivez-vous gratuitement maintenant!',
    register_text:'S\'inscrire',
    password_text:'Mot de passe',
    email_address_text:'Adresse mail',
    forgotpassword_text:"Mot de passe oublié ?",
    new_coplete_text:'Nouveau complete',
    telephone_text:'Telephone',
    prenom_text:'Prenom',
    Nom_de_familee:'Nom de familee',
    Addresse_text:   "Addresse",
    Anniversarie_text:  ' Anniversarie',
    Homme_text:'Homme',
    Moyen_text: 'Moyen de paiement',
    Type_de_client_text:'Type de client',
    Particulier_text:    'Particulier',
    Entreprise_text:     'Entreprise',
    Clienten_compte_text:   'Client en compte',
    Sélectionnezun_avatar_text:   ' Sélectionnez un avatar',
    Ajouter_une_photo_text: 'Ajouter une photo',
    Prendre_votre_photo_text: 'Prendre votre photo',
    J_accepte_les_text: 'J accepte les',
    term_cinditions: ' termes et conditions',
    hop_assist:' d Hop assist',
    Inscrire_Maintenant_text:' Inscrire Maintenant',
    Veuillez_remplir_text: 'Veuillez remplir les champs obligatoires pour continuer',
    Adresse_de_dépannage_text:'Adresse de dépannage',
    Complement_De_Adresse_text:'Complement De Adresse',
    Quelle_text:'Quelle Est La Panne', 
    Veuillez_indiquer_text:'Veuillez indiquer les informations permettsnt a notre expert d\'intervenir chez vous',
    street_text:'Rue',
    zip_code_text:'Code postal',
    city_text:'Ville',
    door_code_text:'Code porte',
    floor_level_text:'Etage',
    other_text:'Autres',
    next_text:'Suivant',
    cancel_text:'Annuler',
    Magasins_disponibles:'Magasins disponibles',
    Quel_est_text:'Quel est l\'appareil concerné ?',
    createReservation_text:'Créer une demande de réservation',
    je_souhaite_text:'Je souhaite être entretenu(e)',
    À_partir_de_text:'À partir de',
    le_text:'Le',
    Aidez_nous_text:'Aidez-nous à comprendre votre problème',
    wait_aduio_photo_text:'Par écrit  et/ou  par audio et/ou  par photo',
    dites_nous_text:'Dites-nous quelle est votre demande :',
    start_recording_text:'Commencer l’enregistrement',
    add_photo_text:'Ajouter des photos ici',
    si_vous_prenez_text:'Si vous prenez une photo du N°de série de votre appareil, cela nous renseignera sur le type de votre appareil (marque/modèle/etc.)',
    Paiement_par_text:'Paiement par',
    visa_Text:' Avec ma carte enregistrée   Visa **** **99',
    other_card_text:'Autre carte',
    reference_text:'Référence Client :   999999',
    add_card_text:'Ajouter une carte',
    Veuillez_renseigner_text:'Veuillez renseigner votre moyen de paiement',
    type_de_card_text:'Type de carte',
    numero_de_text:'Numéro de carte de crédit',
    Expire_le_text:'Expire le',
    Month_text:'Month', 
    Cryptogramme_text:'Cryptogramme visuel',
    lorem_ipsum_has_text:'Lorem Ipsum has been the industry\'s standard dummy text ever since',
    text_ever_since_text:'text ever since',
    Retour_text:'Retour',
    credit_cart_add:'Carte de Credit correctement  ajoute',
    list_expert_text:'Liste des experts',
    list_disponibles_text:'Liste des experts disponibles pour votre commande',
    pour_votre_text:'Pour votre sécurité, Hop-Assist a vérifié l\'identité et l\'identité de l\'utilisateur. les compétences de chaque expert',
    des_experts_text:'Des experts sont à votre disposition pour vous aider',
    cout_text:'Coût / heure',
    travaux_text:' Travaux Effectues',
    suprimer_text:'Suprimer',
    details_expert_text:'Détails de l\'expert',
    intervention_text:'Intervention',
    descripation_Personelle_text:'Descripation Personelle:',
    lorem_dolor_text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    selectionnerr_text:'Selectionnerr',
    voter_command_text:'Votre commande est confirmée',
    annuler_la_text:'Annuler la Commande',
    estimation_text:'Estimation Du travail',
    l_expert_text:'L\'expert arrive sur place et a fait cette estimation',
    temps_text:'Temps',
    cout_traval_text:'Coût / heure ou travail',
    cout_du_materiel_text:'Coût du materiel',
    frais_de_text:'Frais de connexion d\'Hopassist',
    cout_total_text:'Coût total',
    accepter_text:'Accepter',
    votre_expert_text:'Votre Expert Démarrer la commande',
    est_sur_text:'John Smith est sur le point de commencer la commande que vous avez réservée',
    votre_route_text:'Votre Expert est en route',
    vos_remerciements_text:'Vos remerciements pour votre confiance',
    l_expert_arrive_text:'L\'expert est arrivé',
    votre_arrive_text:'Votre Expert John est arrivé',
    etse_vous_text:'Etes-vous sur de vouloir annuler?',
    attendre_trop_text:'Attendre trop longtemps',
    j_ai_text:'J\'ai change d\'avis',
    j_ai_trouve_text:'J\'ai trouvé une autre solution',
    j_ai_fait_text:'J\'ai fait une mauvaise reservation',
    autre_text:'Autre',
    penalite_text:'Pénalité imposée',
    vous_avez_text:'Vous avez facturé le montant suivant parce que l\'expert est en route',
    avis_text:'Avis De L\'utilisateur',
    ou_commenter_text:'Ou commenter',
    confirmer_text:'Confirmer',
    profile_text:'Profil',
    history_text:'Historique',
    notificatiin_text:'Notifications',
    devenir_text:'Devenir Expert',
    a_propos_text:'A Propos de nous',
    faq_text:'FAQ',
    logout_text:'Se déconnecter,',
    a_venir_text:'A venir',
    histoire_text:'Histoire',
    l_intervention_text:'Historique de l\'intervention',
    information_text:'Information de la commande',
    information_expert_text:'Information de la expert ',
    status_text:'Statut',
    numero_identification_text:'Numéro d\'identification du voyage',
    temp_de_text:'Temps de travail',
    category_text:'Categorie',
    mots_text:'Mots cles',
    commande_text:'Commande cree',
    lis_tout_text:'Lis tout',
    
}
export default Application_Constant;